package code_10_math;

import org.junit.Test;

/**
 * 389. Find the Difference
 *
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t.
 *
 * Example:
 Input:
 s = "abcd"
 t = "abcde"

 Output:
 e
 Explanation:
 'e' is the letter that was added.
 */
public class Code_389_FindTheDifference {
    public char findTheDifference(String s, String t) {
        //注意s有可能是空字符串
        if(s.length()==0 && t.length()==1){
            return t.charAt(0);
        }
        char ret=s.charAt(0);
        for(int i=1;i<s.length();i++){
            ret^=s.charAt(i);
        }
        for(int i=0;i<t.length();i++){
            ret^=t.charAt(i);
        }
        return ret;
    }

    @Test
    public void test(){
        String s = "abcd";
        String t = "abcde";
        System.out.println(findTheDifference(s,t));
    }
}
